### ISSUE TITLE
jumboDB-1.0 (seems) to not be using more than 1 core and running for more than 16 hours on ~30x coverage for ~700 Mbp haploid genome size

### ISSUE THREAD

**Issue by jelber2** [AntonBankevich/jumboDB#1]
So, I am using `jumboDB-1.0` on HiFi reads from a Dipteran fly (conversion from subreads to HiFi based on default options for PacBio's `ccs` program) with approximately ~700 Mbp haploid genome size. I've used `hifiasm` and `IPA`, and they seem to be fine. I was just trying out `jumboDB`, and I am using 75 cores (80 core machine), but as far as I can tell `jumboDB` has been using a single core for a lot of the computations.

Here are some stats about the HiFi reads

    /genetics/elbers/bbmap-38.87/readlength.sh bin=1000 in=HiFi-reads-rm-icecream-rm-contam5.fasta.gz|column -ts $'\t'
    Executing jgi.MakeLengthHistogram [bin=1000, in=HiFi-reads-rm-icecream-rm-contam5.fasta.gz]

    Processed 2181848 reads.
    Time: 	190.218 seconds.
    #Reads:                  2181848
    #Bases:                  23307448940
    #Max:                    38618
    #Min:                    45
    #Avg:                    10682.4
    #Median:                 10000
    #Mode:                   10000
    #Std_Dev:                3705.3
    #Read Length Histogram:
    #Length                  reads        pct_reads  cum_reads  cum_pct_reads  bases       pct_bases  cum_bases    cum_pct_bases
    0                        447          0.020%     2181848    100.000%       109864      0.000%     23307448940  100.000%
    1000                     503          0.023%     2181401    99.980%        822712      0.004%     23307339076  100.000%
    2000                     4257         0.195%     2180898    99.956%        11404894    0.049%     23306516364  99.996%
    3000                     28103        1.288%     2176641    99.761%        101626369   0.436%     23295111470  99.947%
    4000                     69510        3.186%     2148538    98.473%        316029106   1.356%     23193485101  99.511%
    5000                     105730       4.846%     2079028    95.287%        584238441   2.507%     22877455995  98.155%
    6000                     139770       6.406%     1973298    90.442%        911390360   3.910%     22293217554  95.648%
    7000                     178125       8.164%     1833528    84.036%        1339121476  5.745%     21381827194  91.738%
    8000                     217733       9.979%     1655403    75.872%        1853671378  7.953%     20042705718  85.993%
    9000                     248873       11.407%    1437670    65.892%        2365696857  10.150%    18189034340  78.040%
    10000                    251476       11.526%    1188797    54.486%        2639043217  11.323%    15823337483  67.890%
    11000                    225451       10.333%    937321     42.960%        2589431831  11.110%    13184294266  56.567%
    12000                    184077       8.437%     711870     32.627%        2297082455  9.856%     10594862435  45.457%
    13000                    143210       6.564%     527793     24.190%        1930003848  8.281%     8297779980   35.601%
    14000                    108353       4.966%     384583     17.626%        1568643728  6.730%     6367776132   27.321%
    15000                    81822        3.750%     276230     12.660%        1266177053  5.432%     4799132404   20.591%
    16000                    61814        2.833%     194408     8.910%         1018519803  4.370%     3532955351   15.158%
    17000                    46670        2.139%     132594     6.077%         815451243   3.499%     2514435548   10.788%
    18000                    33041        1.514%     85924      3.938%         610226660   2.618%     1698984305   7.289%
    19000                    22516        1.032%     52883      2.424%         438254502   1.880%     1088757645   4.671%
    20000                    14455        0.663%     30367      1.392%         295674319   1.269%     650503143    2.791%
    21000                    8382         0.384%     15912      0.729%         179787619   0.771%     354828824    1.522%
    22000                    4163         0.191%     7530       0.345%         93405066    0.401%     175041205    0.751%
    23000                    1949         0.089%     3367       0.154%         45665341    0.196%     81636139     0.350%
    24000                    822          0.038%     1418       0.065%         20074647    0.086%     35970798     0.154%
    25000                    317          0.015%     596        0.027%         8064608     0.035%     15896151     0.068%
    26000                    122          0.006%     279        0.013%         3221663     0.014%     7831543      0.034%
    27000                    62           0.003%     157        0.007%         1703330     0.007%     4609880      0.020%
    28000                    31           0.001%     95         0.004%         881535      0.004%     2906550      0.012%
    29000                    19           0.001%     64         0.003%         559997      0.002%     2025015      0.009%
    30000                    10           0.000%     45         0.002%         304508      0.001%     1465018      0.006%
    31000                    17           0.001%     35         0.002%         536817      0.002%     1160510      0.005%
    32000                    3            0.000%     18         0.001%         97824       0.000%     623693       0.003%
    33000                    7            0.000%     15         0.001%         233978      0.001%     525869       0.002%
    35000                    4            0.000%     8          0.000%         141909      0.001%     291891       0.001%
    36000                    2            0.000%     4          0.000%         73170       0.000%     149982       0.001%
    38000                    2            0.000%     2          0.000%         76812       0.000%     76812        0.000%

I tried kmergenie-1.7051 to "estimate" an optimum k-mer length (I understand that this might not be the best method, but I tried it nonetheless).

    $ mkdir -p kmergenie
    $ cd kmergenie
    $ /genetics/elbers/kmergenie-1.7051/kmergenie --one-pass -s 500 -k 7000 -l 250 ../HiFi-reads-rm-icecream-rm-contam5.fasta \
    > kmergenie.log 2>&1 &
    # best k=991

    $ /genetics/elbers/kmergenie-1.7051/kmergenie --one-pass -s 100 -k 1501 -l 201 ../HiFi-reads-rm-icecream-rm-contam5.fasta \
    > kmergenie.log 2>&1 &
    # best k=1001

    $ /genetics/elbers/kmergenie-1.7051/kmergenie --one-pass -s 20 -k 1201 -l 901 ../HiFi-reads-rm-icecream-rm-contam5.fasta \
    > kmergenie.log 2>&1 &
    # best k=1021

Now, I tried `jumboDB-1.0` with the reads and a k-mer of 1021

    $ bestK=1021
    $ cd /genetics/fly/genome-HiFi/ccs
    $ mkdir -p k${bestK}
    $ /genetics/elbers/jumboDB-1.0/bin/jumboDB -o k${bestK} --reads HiFi-reads-rm-icecream-rm-contam5.fasta.gz -t 75 -k ${bestK} > k${bestK}/k${bestK}.log 2>&1

The dbg.log up to this point

    $ cat dbg.log
    /genetics/elbers/jumboDB-1.0/bin/jumboDB -o k1021 --reads HiFi-reads-rm-icecream-rm-contam5.fasta.gz -t 75 -k 1021 
    00:00:00 0Mb  INFO: Reading reads
    00:00:00 3Mb  INFO: Extracting minimizers
    00:00:00 3Mb  INFO: Starting parallel calculation
    00:03:42 1.1Gb  INFO: 106806 items of total length 1073749831 processed 
    00:07:24 1.1Gb  INFO: 104680 items of total length 1073746087 processed 
    00:11:08 1.2Gb  INFO: 101923 items of total length 1073752033 processed 
    00:14:51 1.2Gb  INFO: 101933 items of total length 1073750142 processed 
    00:18:34 1.2Gb  INFO: 100825 items of total length 1073759285 processed 
    00:22:18 1.3Gb  INFO: 100175 items of total length 1073744423 processed 
    00:26:01 1.3Gb  INFO: 99917 items of total length 1073751218 processed 
    00:29:44 1.3Gb  INFO: 99523 items of total length 1073756251 processed 
    00:33:35 1.3Gb  INFO: 99285 items of total length 1073748668 processed 
    00:37:28 1.3Gb  INFO: 99251 items of total length 1073752846 processed 
    00:41:24 1.3Gb  INFO: 99371 items of total length 1073749917 processed 
    00:45:32 1.4Gb  INFO: 99344 items of total length 1073746973 processed 
    00:49:46 1.4Gb  INFO: 98735 items of total length 1073748417 processed 
    00:53:55 1.4Gb  INFO: 98752 items of total length 1073760680 processed 
    00:58:22 1.4Gb  INFO: 99057 items of total length 1073744031 processed 
    01:02:33 1.4Gb  INFO: 98907 items of total length 1073748822 processed 
    01:06:54 1.4Gb  INFO: 98995 items of total length 1073747061 processed 
    01:11:40 1.4Gb  INFO: 100374 items of total length 1073750626 processed 
    01:15:58 1.4Gb  INFO: 100189 items of total length 1073749935 processed 
    01:20:33 1.4Gb  INFO: 99675 items of total length 1073742671 processed 
    01:25:06 1.4Gb  INFO: 101069 items of total length 1073746100 processed 
    01:28:19 1.4Gb  INFO: 73062 items of total length 758702923 processed 
    01:28:19 1.4Gb  INFO: Finished parallel processing. Processed 2181848 items with total length 23307448940
    01:28:19 1.4Gb  INFO: Finished read processing
    01:28:19 1.4Gb  INFO: 18888046 hashs collected. Starting sorting.
    01:28:24 1.4Gb  INFO: Finished sorting. Total distinct minimizers: 11212539
    01:28:24 1.4Gb  INFO: Starting construction of sparse de Bruijn graph
    01:28:54 5.1Gb  INFO: Vertex map constructed.
    01:28:54 5.1Gb  INFO: Starting to fill edges
    01:28:54 5.1Gb  INFO: Starting parallel calculation
    01:43:13 7.3Gb  INFO: 106806 items of total length 1073749831 processed 
    01:57:10 8.4Gb  INFO: 104680 items of total length 1073746087 processed 
    02:12:16 9.3Gb  INFO: 101923 items of total length 1073752033 processed 
    02:25:45 10.3Gb  INFO: 101933 items of total length 1073750142 processed 
    02:40:24 11.1Gb  INFO: 100825 items of total length 1073759285 processed 
    02:53:24 12Gb  INFO: 100175 items of total length 1073744423 processed 
    03:07:58 12.8Gb  INFO: 99917 items of total length 1073751218 processed 
    03:18:39 13.6Gb  INFO: 99523 items of total length 1073756251 processed 
    03:29:08 14.4Gb  INFO: 99285 items of total length 1073748668 processed 
    03:41:13 15.2Gb  INFO: 99251 items of total length 1073752846 processed 
    03:53:58 16Gb  INFO: 99371 items of total length 1073749917 processed 
    04:07:11 16.7Gb  INFO: 99344 items of total length 1073746973 processed 
    04:20:41 17.5Gb  INFO: 98735 items of total length 1073748417 processed 
    04:43:30 18.2Gb  INFO: 98752 items of total length 1073760680 processed 
    05:02:06 18.9Gb  INFO: 99057 items of total length 1073744031 processed 
    05:17:07 19.7Gb  INFO: 98907 items of total length 1073748822 processed 
    05:40:50 20.4Gb  INFO: 98995 items of total length 1073747061 processed 
    05:52:10 21.1Gb  INFO: 100374 items of total length 1073750626 processed 
    06:04:34 21.9Gb  INFO: 100189 items of total length 1073749935 processed 
    06:16:05 22.6Gb  INFO: 99675 items of total length 1073742671 processed 
    06:26:21 23.3Gb  INFO: 101069 items of total length 1073746100 processed 
    06:33:45 23.5Gb  INFO: 73062 items of total length 758702923 processed 
    06:33:46 23.5Gb  INFO: Finished parallel processing. Processed 2181848 items with total length 23307448940
    06:33:46 23.5Gb  INFO: Sparse graph edges filled.
    06:33:46 23.5Gb  INFO: Checking vertex sequences
    06:33:46 23.5Gb  INFO: Starting parallel calculation
    06:33:46 23.5Gb  INFO: Processed 1048576 items
    06:33:46 23.5Gb  INFO: Processed 1048576 items
    06:33:46 23.5Gb  INFO: Processed 1048576 items
    06:33:46 23.5Gb  INFO: Processed 1048576 items
    06:33:47 23.5Gb  INFO: Processed 1048576 items
    06:33:47 23.5Gb  INFO: Processed 1048576 items
    06:33:47 23.5Gb  INFO: Processed 1048576 items
    06:33:47 23.5Gb  INFO: Processed 1048576 items
    06:33:47 23.5Gb  INFO: Processed 1048576 items
    06:33:48 23.5Gb  INFO: Processed 1048576 items
    06:33:48 23.5Gb  INFO: Processed 726779 items
    06:33:48 23.5Gb  INFO: Finished parallel processing. Processed 11212539 items 
    06:33:48 23.5Gb  INFO: Vertex sequence check success
    06:33:48 23.5Gb  INFO:  Collecting tips 
    06:33:48 23.5Gb  INFO: Starting parallel calculation
    06:37:29 23.9Gb  INFO: Processed 1048576 items
    06:40:53 25Gb  INFO: Processed 1048576 items
    06:44:03 26.1Gb  INFO: Processed 1048576 items
    06:47:06 26.8Gb  INFO: Processed 1048576 items
    06:50:09 27.7Gb  INFO: Processed 1048576 items
    06:53:11 28.6Gb  INFO: Processed 1048576 items
    06:56:23 29.4Gb  INFO: Processed 1048576 items
    06:59:28 30.3Gb  INFO: Processed 1048576 items
    07:02:35 31.1Gb  INFO: Processed 1048576 items
    07:05:44 32Gb  INFO: Processed 1048576 items
    07:07:57 32.6Gb  INFO: Processed 726779 items
    07:07:57 32.6Gb  INFO: Finished parallel processing. Processed 11212539 items 
    07:07:57 32.6Gb  INFO: Added 2295916 artificial minimizers from tips.
    07:07:57 32.6Gb  INFO: Collected 28637006 old edges.
    07:08:08 32.6Gb  INFO: New minimizers added to sparse graph.
    07:08:08 32.6Gb  INFO: Refilling graph with edges.
    07:08:08 32.6Gb  INFO: Starting to fill edges
    07:08:08 32.6Gb  INFO: Starting parallel calculation
    07:14:22 32.7Gb  INFO: 556954 items of total length 1073742604 processed 
    07:20:34 32.9Gb  INFO: 552610 items of total length 1073742528 processed 
    07:26:56 33Gb  INFO: 552037 items of total length 1073744507 processed 
    07:35:25 33.2Gb  INFO: 551911 items of total length 1073743846 processed 
    07:43:17 33.3Gb  INFO: 551556 items of total length 1073743752 processed 
    07:51:18 33.5Gb  INFO: 551620 items of total length 1073742714 processed 
    07:59:44 33.7Gb  INFO: 551272 items of total length 1073742558 processed 
    08:08:20 33.8Gb  INFO: 551608 items of total length 1073743049 processed 
    08:17:12 34Gb  INFO: 551512 items of total length 1073742806 processed 
    08:25:37 34.2Gb  INFO: 551368 items of total length 1073741952 processed 
    08:32:32 34.5Gb  INFO: 551679 items of total length 1073742555 processed 
    08:38:53 34.7Gb  INFO: 551481 items of total length 1073742352 processed 
    08:45:15 34.9Gb  INFO: 551817 items of total length 1073743039 processed 
    08:51:36 35.2Gb  INFO: 551906 items of total length 1073742438 processed 
    08:57:57 35.4Gb  INFO: 552013 items of total length 1073743560 processed 
    09:04:17 35.7Gb  INFO: 552071 items of total length 1073742441 processed 
    09:10:40 35.9Gb  INFO: 551786 items of total length 1073742315 processed 
    09:17:02 36.1Gb  INFO: 551927 items of total length 1073743000 processed 
    09:23:24 36.4Gb  INFO: 551731 items of total length 1073744579 processed 
    09:29:47 36.6Gb  INFO: 551750 items of total length 1073742049 processed 
    09:36:09 36.8Gb  INFO: 552078 items of total length 1073742246 processed 
    09:42:32 37Gb  INFO: 552161 items of total length 1073742518 processed 
    09:48:54 37.2Gb  INFO: 552017 items of total length 1073742780 processed 
    09:55:18 37.4Gb  INFO: 551911 items of total length 1073742418 processed 
    10:02:36 37.6Gb  INFO: 551954 items of total length 1073741833 processed 
    10:10:11 37.8Gb  INFO: 552750 items of total length 1073742685 processed 
    10:17:39 38Gb  INFO: 552407 items of total length 1073742574 processed 
    10:24:44 38.1Gb  INFO: 551714 items of total length 1073742019 processed 
    10:32:33 38.3Gb  INFO: 551699 items of total length 1073742873 processed 
    10:40:17 38.5Gb  INFO: 552128 items of total length 1073742767 processed 
    10:47:31 38.6Gb  INFO: 551864 items of total length 1073742612 processed 
    10:55:11 38.8Gb  INFO: 551696 items of total length 1073742821 processed 
    11:03:00 38.9Gb  INFO: 551875 items of total length 1073743422 processed 
    11:10:29 39.1Gb  INFO: 552415 items of total length 1073743992 processed 
    11:18:04 39.2Gb  INFO: 551733 items of total length 1073742896 processed 
    11:25:09 39.3Gb  INFO: 551677 items of total length 1073742011 processed 
    11:32:40 39.5Gb  INFO: 551772 items of total length 1073741903 processed 
    11:40:26 39.6Gb  INFO: 551518 items of total length 1073741980 processed 
    11:47:49 39.7Gb  INFO: 551872 items of total length 1073742916 processed 
    11:55:25 39.8Gb  INFO: 551402 items of total length 1073743116 processed 
    12:03:39 39.9Gb  INFO: 551627 items of total length 1073743164 processed 
    12:11:02 40Gb  INFO: 551442 items of total length 1073743639 processed 
    12:17:28 40.1Gb  INFO: 551975 items of total length 1073742855 processed 
    12:23:55 40.2Gb  INFO: 551306 items of total length 1073742808 processed 
    12:30:26 40.2Gb  INFO: 551366 items of total length 1073743215 processed 
    12:36:51 40.3Gb  INFO: 551566 items of total length 1073742598 processed 
    12:43:16 40.4Gb  INFO: 551312 items of total length 1073742455 processed 
    12:49:40 40.4Gb  INFO: 551512 items of total length 1073742915 processed 
    12:56:05 40.5Gb  INFO: 551542 items of total length 1073743236 processed 
    13:02:30 40.5Gb  INFO: 551947 items of total length 1073742607 processed 
    13:08:55 40.6Gb  INFO: 551489 items of total length 1073743475 processed 
    13:14:37 40.6Gb  INFO: 490670 items of total length 955201312 processed 
    13:14:37 40.6Gb  INFO: Finished parallel processing. Processed 28637006 items with total length 55716085305
    13:14:37 40.6Gb  INFO: Sparse graph edges filled.
    13:14:37 40.6Gb  INFO: Finished fixing sparse de Bruijn graph.
    13:15:00 40.6Gb  INFO: Checking vertex sequences
    13:15:00 40.6Gb  INFO: Starting parallel calculation
    13:15:09 40.6Gb  INFO: Processed 1048576 items
    13:15:09 40.6Gb  INFO: Processed 1048576 items
    13:15:10 40.6Gb  INFO: Processed 1048576 items
    13:15:10 40.6Gb  INFO: Processed 1048576 items
    13:15:10 40.6Gb  INFO: Processed 1048576 items
    13:15:10 40.6Gb  INFO: Processed 1048576 items
    13:15:11 40.6Gb  INFO: Processed 1048576 items
    13:15:11 40.6Gb  INFO: Processed 1048576 items
    13:15:11 40.6Gb  INFO: Processed 1048576 items
    13:15:11 40.6Gb  INFO: Processed 1048576 items
    13:15:12 40.6Gb  INFO: Processed 1048576 items
    13:15:12 40.6Gb  INFO: Processed 1048576 items
    13:15:12 40.6Gb  INFO: Processed 925491 items
    13:15:12 40.6Gb  INFO: Finished parallel processing. Processed 13508403 items 
    13:15:12 40.6Gb  INFO: Vertex sequence check success
    13:15:12 40.6Gb  INFO: Statistics for sparse de Bruijn graph:
    Graph statistics:
    Total edges: 15853390
    Total vertices: 13508403
    Number of end vertices: 1975023
    Number of unbranching vertices: 9299309
    Number of isolated edges 590412 6582485038
    Distribution of degrees:
    0 1975026
    1 21753003
    2 1637625
    3 817084
    4 423667
    5 210495
    6 101412
    7 48127
    8 23148
    9 27219
    Distribution of in/out degrees:
    0 1975023 3 0 0 
    1975023 18598618 657305 276128 245929 
    3 657305 539964 233302 207051 
    0 276128 233302 154026 153628 
    0 245929 207051 153628 227460 
    13:15:36 40.6Gb  INFO: Starting to extract disjointigs.
    13:15:36 40.6Gb  INFO: Extracting linear disjointigs.
    13:15:36 40.6Gb  INFO: Starting parallel calculation
    13:15:42 40.6Gb  INFO: Processed 1048576 items
    13:15:53 40.6Gb  INFO: Processed 1048576 items
    13:16:01 40.6Gb  INFO: Processed 1048576 items
    13:16:08 40.6Gb  INFO: Processed 1048576 items
    13:16:14 40.6Gb  INFO: Processed 1048576 items
    13:16:19 40.6Gb  INFO: Processed 1048576 items
    13:16:24 40.6Gb  INFO: Processed 1048576 items
    13:16:29 40.6Gb  INFO: Processed 1048576 items
    13:16:35 40.6Gb  INFO: Processed 1048576 items
    13:16:42 40.6Gb  INFO: Processed 1048576 items
    13:16:48 40.6Gb  INFO: Processed 1048576 items
    13:16:55 40.6Gb  INFO: Processed 1048576 items
    13:17:01 40.6Gb  INFO: Processed 925491 items
    13:17:01 40.6Gb  INFO: Finished parallel processing. Processed 13508403 items 
    13:17:01 40.6Gb  INFO: Starting parallel calculation
    13:18:55 40.6Gb  INFO: Processed 1048576 items
    13:20:37 40.6Gb  INFO: Processed 1048576 items
    13:22:13 40.6Gb  INFO: Processed 1048576 items
    13:23:42 40.6Gb  INFO: Processed 1048576 items
    13:25:08 40.6Gb  INFO: Processed 1048576 items
    13:26:34 40.6Gb  INFO: Processed 1048576 items
    13:27:58 40.6Gb  INFO: Processed 1048576 items
    13:29:25 40.6Gb  INFO: Processed 1048576 items
    13:30:49 40.6Gb  INFO: Processed 1048576 items
    13:32:15 40.6Gb  INFO: Processed 1048576 items
    13:33:41 40.6Gb  INFO: Processed 1048576 items
    13:35:07 40.6Gb  INFO: Processed 1048576 items
    13:36:24 40.6Gb  INFO: Processed 925491 items
    13:36:24 40.6Gb  INFO: Finished parallel processing. Processed 13508403 items 
    13:36:24 40.6Gb  INFO: Finished extracting linear disjointigs.
    13:36:24 40.6Gb  INFO: Extracting circular disjointigs.
    13:36:24 40.6Gb  INFO: Starting parallel calculation
    13:36:26 40.6Gb  INFO: Processed 1048576 items
    13:36:27 40.6Gb  INFO: Processed 1048576 items
    13:36:27 40.6Gb  INFO: Processed 1048576 items
    13:36:28 40.6Gb  INFO: Processed 1048576 items
    13:36:28 40.6Gb  INFO: Processed 1048576 items
    13:36:29 40.6Gb  INFO: Processed 1048576 items
    13:36:29 40.6Gb  INFO: Processed 1048576 items
    13:36:30 40.6Gb  INFO: Processed 1048576 items
    13:36:30 40.6Gb  INFO: Processed 1048576 items
    13:36:30 40.6Gb  INFO: Processed 1048576 items
    13:36:31 40.6Gb  INFO: Processed 1048576 items
    13:36:31 40.6Gb  INFO: Processed 1048576 items
    13:36:31 40.6Gb  INFO: Processed 925491 items
    13:36:31 40.6Gb  INFO: Finished parallel processing. Processed 13508403 items 
    13:36:31 40.6Gb  INFO: Finished extracting circular disjointigs.
    13:36:44 40.6Gb  INFO: Finished extracting 6973367 disjointigs of total size 19084795566
    13:46:46 10Mb  INFO: Loading disjointigs from file "k1021/disjointigs.fasta"
    13:52:43 52.1Gb  INFO: Filling bloom filter with k+1-mers.
    13:52:43 52.1Gb  INFO: Starting parallel calculation
    14:14:08 52.1Gb  INFO: 67441 items of total length 1073742673 processed 
    14:40:07 52.1Gb  INFO: 81574 items of total length 1073743864 processed 
    15:05:35 52.1Gb  INFO: 98471 items of total length 1073746007 processed 
    15:31:15 52.1Gb  INFO: 119271 items of total length 1073749300 processed 
    15:55:37 52.1Gb  INFO: 150064 items of total length 1073747087 processed 
    16:18:22 52.1Gb  INFO: 192638 items of total length 1073743915 processed 
    16:40:25 52.1Gb  INFO: 243585 items of total length 1073742854 processed
    17:02:23 52.1Gb  INFO: 298421 items of total length 1073742693 processed
    17:25:31 52.1Gb  INFO: 353896 items of total length 1073743703 processed 
    17:44:23 52.1Gb  INFO: 410400 items of total length 1073742946 processed 
    18:05:18 52.1Gb  INFO: 464594 items of total length 1073742360 processed 
    18:18:17 52.1Gb  INFO: 511525 items of total length 1073742671 processed 
    18:30:54 52.1Gb  INFO: 526779 items of total length 1073743719 processed 
    18:43:03 52.1Gb  INFO: 545605 items of total length 1073742197 processed 
    18:53:30 52.1Gb  INFO: 621230 items of total length 1073742492 processed 
    19:01:50 52.1Gb  INFO: 712122 items of total length 1073742712 processed 
    19:07:32 52.2Gb  INFO: 824376 items of total length 1073742143 processed 
    19:09:18 52.2Gb  INFO: 756861 items of total length 836753436 processed 
    19:09:18 52.2Gb  INFO: Finished parallel processing. Processed 6978853 items with total length 19090396772
    19:12:24 52.2Gb  INFO: Filled 53519679061 bits out of 382879611488
    19:12:24 52.2Gb  INFO: Finished filling bloom filter. Selecting junctions.
    19:12:24 52.2Gb  INFO: Starting parallel calculation
    20:37:30 52.2Gb  INFO: 67441 items of total length 1073742673 processed 
    22:08:39 52.2Gb  INFO: 81574 items of total length 1073743864 processed 
    23:39:35 52.2Gb  INFO: 98471 items of total length 1073746007 processed 
    24:53:35 52.2Gb  INFO: 119271 items of total length 1073749300 processed 
    26:02:04 52.2Gb  INFO: 150064 items of total length 1073747087 processed 
    27:07:43 52.3Gb  INFO: 192638 items of total length 1073743915 processed 
    28:09:59 52.3Gb  INFO: 243585 items of total length 1073742854 processed 
    29:07:12 52.4Gb  INFO: 298421 items of total length 1073742693 processed 
    29:59:48 52.4Gb  INFO: 353896 items of total length 1073743703 processed 
    30:48:07 52.4Gb  INFO: 410400 items of total length 1073742946 processed 
    31:32:27 52.4Gb  INFO: 464594 items of total length 1073742360 processed 
    32:13:24 52.4Gb  INFO: 511525 items of total length 1073742671 processed 
    32:53:07 52.7Gb  INFO: 526779 items of total length 1073743719 processed 
    33:31:29 52.7Gb  INFO: 545605 items of total length 1073742197 processed 
    34:04:17 52.7Gb  INFO: 621230 items of total length 1073742492 processed 
    34:30:17 52.7Gb  INFO: 712122 items of total length 1073742712 processed 
    34:47:50 52.7Gb  INFO: 824376 items of total length 1073742143 processed 
    34:52:56 52.7Gb  INFO: 756861 items of total length 836753436 processed 
    34:52:56 52.7Gb  INFO: Finished parallel processing. Processed 6978853 items with total length 19090396772
    34:53:03 53.5Gb  INFO: Collected 14452238 junctions.
    34:53:51 53.5Gb  INFO: Starting DBG construction.
    34:54:13 53.5Gb  INFO: Vertices created.
    34:54:13 53.5Gb  INFO: Starting parallel calculation
    35:05:52 53.5Gb  INFO: 62337 items of total length 1073752221 processed 
    35:17:20 53.5Gb  INFO: 81662 items of total length 1073748035 processed 
    35:28:39 53.5Gb  INFO: 98564 items of total length 1073742093 processed 
    35:39:47 53.5Gb  INFO: 119401 items of total length 1073746394 processed 
    35:50:41 53.5Gb  INFO: 150257 items of total length 1073744171 processed 
    36:01:12 53.5Gb  INFO: 192886 items of total length 1073742821 processed 
    36:11:12 53.5Gb  INFO: 243865 items of total length 1073745610 processed 
    36:20:39 53.5Gb  INFO: 298711 items of total length 1073743152 processed 
    36:29:25 53.5Gb  INFO: 354187 items of total length 1073742208 processed 
    36:37:35 53.5Gb  INFO: 410695 items of total length 1073744206 processed 
    36:45:08 53.5Gb  INFO: 464862 items of total length 1073743104 processed 
    36:52:06 53.5Gb  INFO: 511715 items of total length 1073743520 processed 
    36:58:41 53.5Gb  INFO: 526787 items of total length 1073743511 processed 
    37:05:04 53.5Gb  INFO: 545879 items of total length 1073743220 processed 
    37:10:37 53.5Gb  INFO: 621672 items of total length 1073742291 processed 
    37:15:03 53.5Gb  INFO: 712638 items of total length 1073742819 processed 
    37:18:10 53.5Gb  INFO: 825061 items of total length 1073741970 processed 
    37:19:22 53.5Gb  INFO: 752188 items of total length 831144220 processed 
    37:19:22 53.5Gb  INFO: Finished parallel processing. Processed 6973367 items with total length 19084795566
    37:19:22 53.5Gb  INFO: Filled dbg edges. Adding hanging vertices 
    37:19:22 53.5Gb  INFO: Starting parallel calculation
    37:19:23 53.5Gb  INFO: Processed 1048576 items
    37:19:25 53.5Gb  INFO: Processed 1048576 items
    37:19:25 53.5Gb  INFO: Processed 1048576 items
    37:19:26 53.5Gb  INFO: Processed 1048576 items
    37:19:26 53.5Gb  INFO: Processed 1048576 items
    37:19:27 53.5Gb  INFO: Processed 1048576 items
    37:19:27 53.5Gb  INFO: Processed 1048576 items
    37:19:28 53.5Gb  INFO: Processed 1048576 items
    37:19:28 53.5Gb  INFO: Processed 1048576 items
    37:19:29 53.5Gb  INFO: Processed 1048576 items
    37:19:29 53.5Gb  INFO: Processed 1048576 items
    37:19:29 53.5Gb  INFO: Processed 1048576 items
    37:19:30 53.5Gb  INFO: Processed 1048576 items
    37:19:30 53.5Gb  INFO: Processed 820750 items
    37:19:30 53.5Gb  INFO: Finished parallel processing. Processed 14452238 items 
    37:19:30 53.5Gb  INFO: Added 465 hanging vertices
    37:19:30 53.5Gb  INFO: Constructed dbg of size 14452703
    37:19:30 53.5Gb  INFO: Merging edges 
    37:19:30 53.5Gb  INFO: Merging unbranching paths
    37:19:30 53.5Gb  INFO: Merging linear unbranching paths
    37:19:30 53.5Gb  INFO: Starting parallel calculation
    37:19:33 53.5Gb  INFO: Processed 1048576 items
    37:19:38 53.5Gb  INFO: Processed 1048576 items
    37:19:45 53.5Gb  INFO: Processed 1048576 items
    37:19:53 53.5Gb  INFO: Processed 1048576 items
    37:20:04 53.5Gb  INFO: Processed 1048576 items
    37:20:17 53.5Gb  INFO: Processed 1048576 items
    37:20:29 53.5Gb  INFO: Processed 1048576 items
    37:20:42 53.5Gb  INFO: Processed 1048576 items
    37:20:55 53.5Gb  INFO: Processed 1048576 items
    37:21:08 53.5Gb  INFO: Processed 1048576 items
    37:21:20 53.5Gb  INFO: Processed 1048576 items
    37:21:31 53.5Gb  INFO: Processed 1048576 items
    37:21:42 53.5Gb  INFO: Processed 1048576 items
    37:21:50 53.5Gb  INFO: Processed 821215 items
    37:21:50 53.5Gb  INFO: Finished parallel processing. Processed 14452703 items 
    37:21:50 53.5Gb  INFO: Finished merging linear unbranching paths
    37:21:50 53.5Gb  INFO: Merging cyclic paths
    37:21:50 53.5Gb  INFO: Starting parallel calculation
    37:21:51 53.5Gb  INFO: Processed 1048576 items
    37:21:51 53.5Gb  INFO: Processed 1048576 items
    37:21:51 53.5Gb  INFO: Processed 1048576 items
    37:21:51 53.5Gb  INFO: Processed 1048576 items
    37:21:51 53.5Gb  INFO: Processed 1048576 items
    37:21:51 53.5Gb  INFO: Processed 1048576 items
    37:21:52 53.5Gb  INFO: Processed 1048576 items
    37:21:52 53.5Gb  INFO: Processed 1048576 items
    37:21:52 53.5Gb  INFO: Processed 1048576 items
    37:21:52 53.5Gb  INFO: Processed 1048576 items
    37:21:52 53.5Gb  INFO: Processed 1048576 items
    37:21:53 53.5Gb  INFO: Processed 1048576 items
    37:21:53 53.5Gb  INFO: Processed 1048576 items
    37:21:53 53.5Gb  INFO: Processed 821215 items
    37:21:53 53.5Gb  INFO: Finished parallel processing. Processed 14452703 items 
    37:21:53 53.5Gb  INFO: Found 0 perfect loops
    37:21:53 53.5Gb  INFO: Finished merging cyclic paths
    37:21:53 53.5Gb  INFO: Removing isolated vertices
    37:22:38 53.5Gb  INFO: Finished removing isolated vertices
    37:22:38 53.5Gb  INFO: Ended merging edges. Resulting size 10768297
    37:22:38 53.5Gb  INFO: Statistics for de Bruijn graph:
    Graph statistics:
    Total edges: 14195083
    Total vertices: 10768297
    Number of end vertices: 1975026
    Number of unbranching vertices: 0
    Number of isolated edges 404800 4427899784
    Distribution of degrees:
    0 1975026
    1 10742724
    2 8810284
    3 7366
    4 1194
    5 0
    6 0
    7 0
    8 0
    9 0
    Distribution of in/out degrees:
    0 1975026 0 0 0 
    1975026 0 8763160 4253 285 
    0 8763160 45188 1652 284 
    0 4253 1652 1056 405 
    0 285 284 405 220 
    37:22:44 53.5Gb  INFO: Printing graph to fasta file "k1021/graph.fasta"
    38:33:14 53.5Gb  INFO: Printing graph to gfa file "k1021/graph.gfa"
    39:00:19 53.5Gb  INFO: Printing graph to dot file "k1021/graph.dot"
    39:02:52 53.5Gb  INFO: DBG construction finished

I guess this seems to be taking a very long time and also not sure about the `-t 75` option and the amount of memory usage? Maybe it is unique to Dipteran flies?

**Comment by AntonBankevich** [comment]
Fixed in release 1.0.1
