### ISSUE TITLE
Assembly result

### ISSUE THREAD

**Issue by zhoudreames** [AntonBankevich/jumboDB#3]
Hi ~
In recently ,I want to know could this software gain Assembly sequence ?

**Comment by zhoudreames** [comment]
@AntonBankevich

**Comment by AntonBankevich** [comment]
Hi. If I understand you correctly, you are asking if this software can generate genome assemblies. The answer is that this is not a complete genome assembly program but only a module for de Bruijn graph construction. It does not contain error correction or repeat resolution modules. We are currently working on LJA software that will solve these problems and output the assembled sequences.

**Comment by zhoudreames** [comment]
but this software no public,so sad
![image](https://user-images.githubusercontent.com/54714639/117558791-d6d6ca00-b0b2-11eb-80e5-8257894db538.png)
